name: go
on:
  push:
      branches:
        - master

jobs:
  build:
    name: AoC-2018-go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2018/go
        nix-shell -p go --pure --run 'go test ./...'
