name: rust
on:
  push:
      branches:
        - master

jobs:
  build:
    name: AoC-2018-rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - run: |
        cd 2018/rust
        nix-shell -p cargo --pure --run 'cargo test'
