name: 2020-day02-idris2
on:
  push:
      branches:
        - master

jobs:
  build:
    name: AoC-2020-day02-idris2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2020/day02
        nix-shell --run './build.sh && ./run.sh'
