name: 2020-day07-eiffel
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - 2020/day07/**

jobs:
  build:
    name: AoC-2020-day07-eiffel
    runs-on: ubuntu-20.04
    container: eiffel/eiffel:23.09
    steps:
    - uses: actions/checkout@v2.3.4
    - run: |
        cd 2020/day07
        # sudo ./install.sh
        ./build.sh
        ./run.sh
