name: 2020-day13-clojure
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - 2020/day13/**

jobs:
  build:
    name: AoC-2020-day13-clojure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        skip_adding_nixpkgs_channel: true
    - run: |
        cd 2020/day13
        nix-shell
        lein test
        lein uberjar
        java -jar target/uberjar/day13-*-standalone.jar
