name: 2020-day08-cl
on:
  push:
      branches:
        - master
      paths:
        - 2020/day08

jobs:
  build:
    name: AoC-2020-day08-CommonLisp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2020/day08
        ./run.sh
