name: 2020-day07-eiffel
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - 2020/day07/**

jobs:
  build:
    name: AoC-2020-day07-eiffel
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - run: |
        cd 2020/day07
        sudo echo 'deb [trusted=yes] http://apt.liberty-eiffel.org/ release main' >> /etc/apt/sources.list.d/liberty-eiffel.list
        # sudo echo 'deb [trusted=yes] http://apt.liberty-eiffel.org/ release main' >> /etc/apt/sources.list
        apt-get update
        apt-get install liberty-eiffel-all
        # sudo ./install.sh
        ./build.sh
        ./run.sh
