name: 2020-day10-ada
on:
  push:
      branches:
        - master
      paths:
        - 2020/day10

jobs:
  build:
    name: AoC-2020-day10-Ada
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2020/day10
        ./build.sh
        ./day10
