name: 2020-day01-prolog
on:
  workflow_call:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - 2020/day01/**

jobs:
  build:
    name: AoC-2020-day01-prolog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2020/day01
        nix-shell --run './build.sh && ./day01'
