name: 2020-day25-elm
on:
  workflow_call:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "2020/day25/**"

jobs:
  build:
    name: AoC-2020-day25-elm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2020/day25
        ./run.sh



