name: 2020-day15-racket
on:
  push:
      branches:
        - master
      paths:
        - 2020/day15

jobs:
  build:
    name: AoC-2020-day15-racket
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: |
        cd 2020/day15
        ./test.sh
        ./run.sh
