name: 2020-day16-unison
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "2020/day16/**"

jobs:
  build:
    name: AoC-2020-day16-Unison
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2020/day16
        ./build.sh
        ./run.sh

