name: 2020-day09-chapel
on:
  push:
      branches:
        - master

jobs:
  build:
    name: AoC-2020-day09-Chapel
    runs-on: ubuntu-latest
    container: chapel/chapel:1.23.0
    steps:
    - uses: actions/checkout@v2.3.4
    - run: |
        cd 2020/day09
        ./build.sh
        ./day09
