name: 2023-julia
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "2023/**"

jobs:
  build:
    name: AoC-2023-julia
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd 2023
        nix-shell
        julia day01.jl
        julia day02.jl
        julia day03.jl
        julia day04.jl
        julia day06.jl
        julia day07.jl
        julia day08.jl
        julia day09.jl
        julia day10.jl
        julia day15.jl
        julia day19.jl
